// src/lib/Blocks/Parent/Table/Table.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
import BlockControl from "$lib/Blocks/BlockControl.vue"
// import TableHead from "./TableHead.astro"
// import TableRow from "./TableRow.astro"
interface Props {
  blk: TableBlock<IsSingle>
}
const props = defineProps<Props>();
const presets = {
  def: "",
};

const cls = classNaming("", props.blk.classes, props.blk.preset, presets)
</script>

<template>
  <table :id="blk.id" :class="`${cls} table is-fullwidth is-striped is-hoverable`">
    <thead v-if="blk.$th">
      <tr>
        <th v-for="hc in blk.$th">{{ hc }}</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="row in blk.$trs">
        <td v-for="cell in row">
          <BlockControl :blks="[cell]" />
        </td>
      </tr>
    </tbody>
  </table>
</template>

// mlml/lib/Block/Complex/Table/Table.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  import BlockControl from "$lib/Block/BlockControl.svelte";

  export let dtime: number = 0;

  // export let caption: string = '';
  export let blk: TableBlock<IsSingle> = {
    type: "Table",
    $th: [],
    $trs: [],
  };

  const presets = {
    def: "",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<svelte:head />

<div id={blk.id} class="content {cls} {blk.classes}" in:fade={{ delay: dtime }}>
  <table class="table is-fullwidth is-striped is-hoverable">
    {#if blk.$th}
      <thead>
        <tr>
          {#each blk.$th as hc}
            <th>{hc}</th>
          {/each}
        </tr>
      </thead>
    {/if}
    <tbody>
      {#each blk.$trs as tr}
        <tr>
          {#each tr as tc}
            <td>
              <BlockControl blks={[tc]} />
            </td>
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>
</div>
