// src/lib/Blocks/Layout/FlexLayout.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
import BlockControl from "$lib/Blocks/BlockControl.vue"
interface Props {
  blk: FlexLayout<IsSingle>
}
const props = defineProps<Props>();
const presets = {
  def: "is-flex is-flex-wrap-wrap is-justify-content-space-around is-align-items-stretch",
};

const cls = classNaming("", props.blk.classes, props.blk.preset, presets)
</script>

<template>
  <div :id="blk.id" :class="cls">
    <BlockControl v-for="blks in blk.$blkss" :blks="blks" />
  </div>
</template>

<style lang="scss">
</style>

// mlml/lib/Block/Layout/FlexLayout.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  import BlockControl from "../BlockControl.svelte";

  export let dtime: number = 0;

  export let blk: FlexLayout<IsSingle> = {
    type: "FLEX",
    $blkss: [],
  };

  const presets = {
    def: "",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<div
  id={blk.id}
  class="content is-flex is-flex-wrap-wrap is-justify-content-space-around is-align-items-stretch {cls} {blk.classes}"
  in:fade={{ delay: dtime }}
>
  {#each blk.$blkss as blks}
    <BlockControl {blks} />
  {/each}
</div>

<style lang="scss">
</style>
