// mlml/lib/Block/Simple/Plain.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import { fade } from "svelte/transition";
  export let dtime: number = 0;

  export let blk: PlainBlock<string, string[]> = {
    type: "Plain",
    $texts: [],
  };

  const presets = {
    def: "px-3",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<div id={blk.id} class="content {cls} {blk.classes}" in:fade={{ delay: dtime }}>
  {#each blk.$texts as t}
    <p class={blk.classes}>{@html t}</p>
  {/each}
</div>

// src/lib/Blocks/Simple/Plain.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
interface Props {
  blk: PlainBlock<IsSingle>
}
const props = defineProps<Props>();

const presets = {
  def: "px-3",
};

const cls = classNaming("content", props.blk.classes, props.blk.preset, presets)
</script>

<template>
  <div :id="blk.id" :class="cls">
    <p v-for="t in blk.$texts">{{ t }}</p>
  </div>
</template>
