// mlml/lib/Block/Complex/Media/MediaRight.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  import BlockControl from "$lib/Block/BlockControl.svelte";

  export let dtime: number = 0;

  export let blk: MediaTextBlock<IsSingle> = {
    type: "Media Right",
    // $texts: ["Media Right"],
    $blks: [],
    src: "defaultimg.jpg",
    $alt: "Default Image",
  };

  const presets = {
    def: "",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<div
  id={blk.id}
  class="content img-box {cls} {blk.classes}"
  in:fade={{ delay: dtime }}
>
  <div class="mr-2-desktop pl-5-desktop">
    <BlockControl blks={blk.$blks} />
    <!-- {#each blk.$texts as t}
      <p>{t}</p>
    {/each} -->
  </div>
  <img src="{base}{blk.src}" alt={blk.$alt} class="pr-5-desktop" />
</div>

<!-- <div class="is-clearfix" /> -->
<style>
  img {
    display: block;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    margin-top: 0.5rem;
  }
  @media (min-width: 1024px) {
    div.img-box {
      display: flex;
    }
    div.img-box div {
      flex-grow: 1;
    }
    div.img-box img {
      flex-grow: 0;
    }
  }
</style>

// src/lib/Blocks/Parent/Media/MediaRight.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
import BlockControl from "$lib/Blocks/BlockControl.vue"
interface Props {
  blk: MediaTextBlock<IsSingle>
  lang: LangList
}
const props = defineProps<Props>();

const presets = {
  def: "",
};

const cls = classNaming("img-box box", props.blk.classes, props.blk.preset, presets)
</script>


<template>
  <div :id="blk.id" :class="cls">
    <div class="columns">
      <div class="column is-two-thirds ml-2-desktop pr-5-desktop">
        <BlockControl :blks="blk.$blks" :lang="lang" />
      </div>
      <div class="column is-one-third has-text-centered">
        <img :src="blk.src" :alt="blk.$alt" class="img-box-fig" />
      </div>
    </div>
  </div>
</template>

<style scoped>
@media (min-width: 1024px) {
  div.img-box {
    display: flex;
  }

  div.img-box div {
    flex-grow: 1;
  }

  div.img-box img {
    flex-grow: 0;
  }
}
</style>
