// mlml/lib/Block/Simple/List.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  export let dtime: number = 0;

  export let blk: ListBlock<string[]> = {
    type: "List",
    $texts: [],
  };

  const presets = {
    def: "",
    circle: "list-circled",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<ul id={blk.id} class="content {cls} {blk.classes}" in:fade={{ delay: dtime }}>
  {#each blk.$texts as t}
    <li>{@html t}</li>
  {/each}
</ul>

// src/lib/Blocks/Child/List.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
interface Props {
  blk: ListBlock<IsSingle>
}
const props = defineProps<Props>();


const presets = {
  def: "",
  circle: "list-circled",
};

const cls = classNaming("", props.blk.classes, props.blk.preset, presets)
</script>

<template>
  <div class="content">
    <ul :id="blk.id" :class="cls">
      <li v-for="t in blk.$texts">{{ t }}</li>
    </ul>
  </div>
</template>
