// src/lib/Blocks/Child/Define.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
interface Props {
  blk: DefineBlock<IsSingle>
}
const props = defineProps<Props>();

const presets = {
  def: "px-3",
};

const cls = classNaming("", props.blk.classes, props.blk.preset, presets)
</script>

<template>
  <div class="content">
    <dl :id="blk.id" :class="cls">
      <template v-for="item in blk.$texts">
        <dt>{{ item[0] }}</dt>  
        <dd v-for="dts in item.slice(1)">{{ dts }}</dd>
      </template>
    </dl>
  </div>
</template>

// mlml/lib/Block/Simple/Define.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  export let dtime: number = 0;

  export let blk: DefineBlock<string[][]> = {
    type: "Define",
    $texts: [],
  };

  const presets = {
    def: "",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<div id={blk.id} class="content {cls} {blk.classes}">
  <dl in:fade={{ delay: dtime }}>
    {#each blk.$texts as t}
      <dt>{t[0]}</dt>
      {#if t.length > 1}
        {#each t.slice(1) as dd}
          <dd>{dd}</dd>
        {/each}
      {/if}
    {/each}
  </dl>
</div>
