// src/lib/Blocks/BlockControl.vue
<script setup lang="ts">
// import BlkControl from "$lib/Block/BlockControl.vue";
import Plain from "$lib/Blocks/Simple/Plain.vue"
import List from "$lib/Blocks/Simple/List.vue"
import Define from "$lib/Blocks/Simple/Define.vue"
import Link from "$lib/Blocks/Simple/Link.vue"
import Image from "$lib/Blocks/Simple/Image.vue"
import Hd2 from "$lib/Blocks/Simple/Headings/Hd2.vue"
import Hd3 from "$lib/Blocks/Simple/Headings/Hd3.vue"
import Hd4 from "$lib/Blocks/Simple/Headings/Hd4.vue"
import Ih2 from "$lib/Blocks/Simple/Headings/Ih2.vue"
import Ih3 from "$lib/Blocks/Simple/Headings/Ih3.vue"
import Ih4 from "$lib/Blocks/Simple/Headings/Ih4.vue"
import Hero from "$lib/Blocks/Simple/Hero/Hero.vue"
import SubHero from "$lib/Blocks/Simple/Hero/SubHero.vue"
import SubBar from "$lib/Blocks/Simple/Hero/SubBar.vue"
import Relatives from "$lib/Blocks/Simple/Relatives/Relatives.vue"
import Spacer from "$lib/Blocks/Simple/Spacer.vue";
import Separator from "$lib/Blocks/Simple/Separator.vue";

import MediaLeft from "$lib/Blocks/Complex/Media/MediaLeft.vue";
import MediaRight from "$lib/Blocks/Complex/Media/MediaRight.vue";
import Gallary from "./Complex/Gallary/Gallary.vue";
import Features from "./Complex/Features/Features.vue";
import Horizontal from "./Complex/Horizontal/Horizontal.vue";
import Flow from "./Complex/Flow/Flow.vue";
import Table from "./Complex/Table/Table.vue";

import Flexlayout from "./Layout/FlexLayout.vue";
import Columnlayout from "./Layout/ColumnLayout.vue";

interface Props {
  blks: AnyBlock<IsSingle>[]
  // blks: Array<SimpleBlock<IsSingle> | ComplexBlock<IsSingle> | LayoutBlock<IsSingle>>
}
const props = defineProps<Props>();
const presets = {
  def: "",
};
</script>

<template>
  <div class="block px-5-desktop" v-for="blk in blks">
    <Plain v-if="blk.type === 'Plain'" :blk="blk" />
    <List v-else-if="blk.type === 'List'" :blk="blk" />
    <Define v-else-if="blk.type === 'Define'" :blk="blk" />
    <Link v-else-if="blk.type === 'Link'" :blk="blk" />
    <Image v-else-if="blk.type === 'Image'" :blk="blk" />
    <Hd2 v-else-if="blk.type === 'Heading 2'" :blk="blk" />
    <Hd3 v-else-if="blk.type === 'Heading 3'" :blk="blk" />
    <Hd4 v-else-if="blk.type === 'Heading 4'" :blk="blk" />
    <Ih2 v-else-if="blk.type === 'Icon Heading 2'" :blk="blk" />
    <Ih3 v-else-if="blk.type === 'Icon Heading 3'" :blk="blk" />
    <Ih4 v-else-if="blk.type === 'Icon Heading 4'" :blk="blk" />
    <Hero v-else-if="blk.type === 'Hero'" :blk="blk" />
    <SubHero v-else-if="blk.type === 'Sub Hero'" :blk="blk" />
    <SubBar v-else-if="blk.type === 'Sub Bar'" :blk="blk" />
    <Relatives v-else-if="blk.type === 'Relatives'" :blk="blk" />
    <Spacer v-else-if="blk.type === 'Spacer'" :blk="blk" />
    <Separator v-else-if="blk.type === 'Separator'" :blk="blk" />
    <MediaLeft v-else-if="blk.type === 'Media Left'" :blk="blk" />
    <MediaRight v-else-if="blk.type === 'Media Right'" :blk="blk" />
    <Gallary v-else-if="blk.type === 'Gallary'" :blk="blk" />
    <Features v-else-if="blk.type === 'Features'" :blk="blk" />
    <Horizontal v-else-if="blk.type === 'Horizontal'" :blk="blk" />
    <Flow v-else-if="blk.type === 'Flow'" :blk="blk" />
    <Table v-else-if="blk.type === 'Table'" :blk="blk" />
    <Flexlayout v-else-if="blk.type === 'FLEX'" :blk="blk" />
    <Columnlayout v-else-if="blk.type === 'COLUMN'" :blk="blk" />
    <div v-else>
      <p>Iregular block</p>
    </div>
  </div>
</template>

// mlml/lib/Block/BlockControl.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import Plain from "./Simple/Plain.svelte";
  import List from "./Simple/List.svelte";
  import Define from "./Simple/Define.svelte";
  import Link from "./Simple/Link.svelte";
  import Image from "./Simple/Image.svelte";

  import Hero from "./Simple/Hero/Hero.svelte";
  import SubHero from "./Simple/Hero/Subhero.svelte";
  import SubBar from "./Simple/Hero/Subbar.svelte";

  import Hd2 from "./Simple/Headings/Hd2.svelte";
  import Hd3 from "./Simple/Headings/Hd3.svelte";
  import Hd4 from "./Simple/Headings/Hd4.svelte";
  import Ih2 from "./Simple/Headings/Ih2.svelte";
  import Ih3 from "./Simple/Headings/Ih3.svelte";
  import Ih4 from "./Simple/Headings/Ih4.svelte";

  import Relatives from "./Simple/Relatives/Relatives.svelte";
  import Spacer from "./Simple/Spacer.svelte";
  import Separator from "./Simple/Separator.svelte";

  import MediaLeft from "./Complex/Media/MediaLeft.svelte";
  import MediaRight from "./Complex/Media/MediaRight.svelte";
  import Gallary from "./Complex/Gallary/Gallary.svelte";
  import Features from "./Complex/Features/Features.svelte";
  import Horizontal from "./Complex/Horizontal/Horizontal.svelte";
  import Flows from "./Complex/Flow/Flow.svelte";
  import Table from "./Complex/Table/Table.svelte";

  import Flexlayout from "./Layout/FlexLayout.svelte";
  import Columnlayout from "./Layout/ColumnLayout.svelte";

  export let blks: AnyBlock<IsSingle>[];

  const delay = 250;
</script>

<!-- <section class="section"> -->
<div class="contents px-5-desktop">
  {#each blks as blk, idx}
    {#if blk.type === "Heading 2"}
      <Hd2 {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Heading 3"}
      <Hd3 {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Heading 4"}
      <Hd4 {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Icon Heading 2"}
      <Ih2 {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Icon Heading 3"}
      <Ih3 {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Icon Heading 4"}
      <Ih4 {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Plain"}
      <Plain {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Link"}
      <Link {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Image"}
      <Image {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "List"}
      <List {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Define"}
      <Define {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Hero"}
      <Hero {blk} />
    {:else if blk.type === "Sub Hero"}
      <SubHero {blk} />
    {:else if blk.type === "Sub Bar"}
      <SubBar {blk} />
    {:else if blk.type === "Media Right"}
      <MediaRight {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Media Left"}
      <MediaLeft {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Gallary"}
      <Gallary {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Features"}
      <Features {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Horizontal"}
      <Horizontal {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Flow"}
      <Flows {blk} />
    {:else if blk.type === "Table"}
      <Table {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "Spacer"}
      <Spacer {blk} />
    {:else if blk.type === "Separator"}
      <Separator dtime={(idx + 1) * delay} />
    {:else if blk.type === "RawHTML"}
      {@html blk.$html}
    {:else if blk.type === "Relatives"}
      <Relatives {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "FLEX"}
      <Flexlayout {blk} dtime={(idx + 1) * delay} />
    {:else if blk.type === "COLUMN"}
      <Columnlayout {blk} dtime={(idx + 1) * delay} />
    {/if}
  {/each}
</div>
<!-- </section> -->
