// mlml/lib/Block/Complex/Horizontal/Horizontal.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  import BlockControl from "$lib/Block/BlockControl.svelte";

  export let dtime: number = 0;

  export let blk: HorizontalBlock<IsSingle> = {
    type: "Horizontal",
    $items: [],
  };

  const presets = {
    def: "",
  };

  $: cls = presets[blk.preset] || presets.def;

  let sizing = "";

  $: {
    if (blk.$items.length < 3) {
      sizing = "is-one-third";
    } else if (blk.$items.length < 5) {
      sizing = "is-one-quater";
    } else {
      sizing = "is-2";
    }
  }

  function move(link: string) {
    if (!link) {
      return;
    } else {
      goto(link);
    }
  }
</script>

<div id={blk.id} class="content {cls} {blk.classes}" in:fade={{ delay: dtime }}>
  <div class="columns">
    {#each blk.$items as itm}
      <div class="column {sizing}">
        <div class="card my-3 horizontal-card" on:click={() => move(itm.link)}>
          <div class="card-image">
            <figure class="image is-4by4">
              {#if itm.img !== ""}
                <img src={itm.img} alt={itm.$title} />
              {:else}
                <img src="/system/defaultimg.jpg" alt={itm.$title} />
              {/if}
            </figure>
          </div>
          <div class="card-content">
            <div class="media-content px-3">
              <p class="title is-4">{itm.$title}</p>
            </div>
          </div>
          <div class="content p-5">
            <BlockControl blks={itm.$blks} />
          </div>
        </div>
      </div>
    {/each}
  </div>
</div>

<style lang="scss">
  .horizontal-card {
    background-color: rgba(220, 220, 220, 0.5);
  }
</style>

// src/lib/Blocks/Complex/Horizontal/Horizontal.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
import HoriItem from "./HoriItem.vue"
interface Props {
  blk: HorizontalBlock<IsSingle>
}
const props = defineProps<Props>();

const presets = {
  def: "",
};

const cls = classNaming("", props.blk.classes, props.blk.preset, presets)

const size =
  props.blk.$items.length < 3 ? "is-one-third"
    : props.blk.$items.length < 5 ? "is-one-quater"
      : "is-2"
</script>

<template>
  <div :id="blk.id" :class="cls">
    <div class="columns">
      <HoriItem v-for="itm in blk.$items" :itm="itm" :size="size" />
    </div>
  </div>
</template>

<style lang="scss" scoped>
.horizontal-card {
  background-color: rgba(220, 220, 220, 0.5);
}
</style>
