// src/lib/Blocks/Parent/Gallary/Gallary.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
import Image from "$lib/Blocks/Child/Image.vue"
interface Props {
  blk: GallaryBlock<IsSingle>
}
const props = defineProps<Props>();

const presets = {
  def: "",
};

const cls = classNaming("", props.blk.classes, props.blk.preset, presets)
</script>

<template>
  <div :id="blk.id" :class="cls">
    <div class="is-flex is-flex-wrap-wrap is-justify-content-space-around is-align-items-stretch">
      <Image v-for="img in blk.$blks" :blk="img" />
    </div>
  </div>
</template>

<style lang="scss" scoped>
</style>

// mlml/lib/Block/Complex/Gallary/Gallary.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  import ImageBlock from "$lib/Block/Simple/Image.svelte";

  export let dtime: number = 0;

  export let blk: GallaryBlock<IsSingle> = {
    type: "Gallary",
    $blks: [],
  };

  const presets = {
    def: "",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<div id={blk.id} class="content {cls} {blk.classes}" in:fade={{ delay: dtime }}>
  <div
    class="is-flex is-flex-wrap-wrap is-justify-content-space-around is-align-items-stretch"
  >
    {#each blk.$blks as img}
      <ImageBlock blk={img} />
    {/each}
  </div>
</div>

<style lang="scss">
</style>
