// mlml/lib/Block/Layout/ColumnLayout.svelte
<script lang="ts">
  import { fade } from "svelte/transition";
  import BlockControl from "$lib/Block/BlockControl.svelte";

  export let dtime: number = 0;

  export let blk: ColumnLayout<IsSingle> = {
    type: "COLUMN",
    $blkss: [],
  };

  const presets = {
    def: "",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<div
  id={blk.id}
  class="content columns {cls} {blk.classes}"
  in:fade={{ delay: dtime }}
>
  {#each blk.$blkss as blks}
    <div class="column">
      <BlockControl {blks} />
    </div>
  {/each}
</div>

<style lang="scss">
</style>

// src/lib/Blocks/Ancestor/ColumnLayout.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
import BlockControl from "$lib/Blocks/BlockControl.vue"
interface Props {
  blk: ColumnLayout<IsSingle>
}
const props = defineProps<Props>();

const presets = {
  def: "",
};

const cls = classNaming("columns", props.blk.classes, props.blk.preset, presets)
</script>

<template>
  <div :id="blk.id" :class="cls">
    <div class="column" v-for="blks in blk.$blkss">
      <BlockControl :blks="blks" />
    </div>
  </div>
</template>

<style lang="scss">
</style>
