// mlml/lib/Block/Simple/Hero/Subbar.svelte
<script lang="ts">
  export let blk: SubBarBlock<string> = {
    type: "Sub Bar",
    $title: "",
  };

  const presets = {
    def: "is-small is-primary",
  };

  $: cls = presets[blk.preset] || presets.def;
</script>

<section class="hero {cls}">
  <div class="hero-body">
    <h1 class="title">{blk.$title}</h1>
  </div>
</section>

<style>
  h1 {
    text-align: center;
  }
</style>

// src/lib/Blocks/Child/Hero/SubBar.vue
<script setup lang="ts">
import { classNaming } from "$scripts/_className"
interface Props {
  blk: SubBarBlock<IsSingle>
}
const props = defineProps<Props>();

const presets = {
  def: "",
};

const cls = classNaming("", props.blk.classes, props.blk.preset, presets)
</script>

<template>
  <section :class="cls">
    <div class="aries-subbar">
      <h1 class="aries-subbar-title">{{ blk.$title }}</h1>
    </div>
  </section>
</template>

<style lang="scss" scoped>
@use "../../../../styles/colors.scss" as c;
h1 {
  text-align: center;
}
div.aries-subbar {
  background-color: c.$primary-nega;
  color: c.$primary-nega-text;
}
</style>
